services:
  db:
    image: postgres:16-alpine
    container_name: learnflow-db
    restart: always
    environment:
      POSTGRES_USER: learnflow
      POSTGRES_PASSWORD: learnflow
      POSTGRES_DB: learnflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U learnflow -d learnflow" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: learnflow-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  web:
    build: .
    container_name: learnflow-django
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - learnflow-network

  worker:
    build: .
    container_name: learnflow-worker
    command: celery -A learnflow worker -l INFO -Q email,notifications,default
    volumes:
      - .:/app
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - learnflow-network

  beat:
    build: .
    container_name: learnflow-beat
    command: celery -A learnflow beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - learnflow-network

networks:
  learnflow-network:
    driver: bridge

volumes:
  postgres_data: